# Generated by Django 3.1.2 on 2020-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('quiz_type', models.TextField()),
                ('timestamp', models.PositiveBigIntegerField()),
                ('goal', models.PositiveBigIntegerField()),
                ('indicator_value', models.FloatField()),
                ('vote_detail', models.JSONField()),
            ],
        ),
    ]
